<style type="text/css">
    #zenc-email-logger {
        width: 100%;
        clear: both;
    }
    #jsGridWrapper {
        float: left;
        width: 55%;
        margin-right: 20px;
    }
    #jsViewWrapper {
        float: left;
        width: 43%;
        overflow-x: hidden;
        overflow-y: auto;
        position: relative;
    }
    #jsViewWrapper iframe {
        width: 100%;
        height: 360px;
        border: 1px solid #999;
        margin-bottom: 20px;
        overflow: auto;
        position: absolute;
        top: 0;
        left: 0;
    }
    #jsViewWrapper div {
        width: 100%;
        margin-top: 360px;
    }

    @media(max-width: 1200px) {
        #jsGridWrapper, #jsViewWrapper {
            float: none;
            width: 100%;
        }
    }
</style>

<div id="zenc-email-logger">
    <div id="jsGridWrapper">
        <div id="jsGrid"></div>
    </div>
    <div id="jsViewWrapper" class="jsgrid-grid-body">
        Click on an item on the left to see it's contents
        <div id="jsView"></div>
    </div>
</div>

<script type="text/javascript">

    typeof jQuery == 'undefined' ? document.getElementsByTagName('head')[0].appendChild(
         document.createElement('srcipt').setAttribute('src', 'https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.min.js')
    );

    (function($) {

        $('head').append($('<script />').attr('src', 'https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.3.1/jsgrid.min.js'));

        function renderTable(data) {
            var $table = $('<table></table>').addClass('jsgrid-table');

            $.each(data, function(key, value) {
                var $row = $('<tr><td /><td /></tr>');

                $row.find('td:first').css('fontWeight', 'bold').text(
                    !$.isNumeric(key) ? key.replace(/_/g, ' ') : key
                );

                if ($.isPlainObject(value) ||$.isArray(value) || typeof value == 'Object') {
                    $row.find('td:last').append(renderTable(value));
                } else {
                    $row.find('td:last').text(value);
                }
                $table.append($row);
            });
            $table.find('tr:even').addClass('jsgrid-row');
            $table.find('tr:odd').addClass('jsgrid-row');
            $table.find('tr td:first-child').width(130);

            return $table;
        }

        $("#jsGrid").jsGrid({
            width: "100%",

            autoload: true,
            pageLoading: true,
            paging: true,

            rowClick: function(data) {
                $.ajax({
                    type: "GET",
                    url: "<?php echo Mage::getUrl('zenc_emaillogger/rest/read') ?>",
                    data: {id: data.item.id},
                    dataType: "json",
                    success: function(data) {
                        $('#jsViewWrapper').empty()
                            .append(
                                $('<iframe />').attr('src', "<?php echo Mage::getUrl('zenc_emaillogger/rest/read') ?>?format=html&id=" + data.mail_id)
                                    .width($('#jsViewWrapper').width() - 2)
                            )
                            .append($('<div />').append(renderTable(data)))
                            .height($('#jsGrid').height());
                    }
                });
            },

            controller: {
                loadData: function(filter) {
                    return $.ajax({
                        type: "GET",
                        url: "<?php echo Mage::getUrl('zenc_emaillogger/rest/list') ?>?format=json",
                        data: filter,
                        dataType: "json"
                    });
                }
            },
            fields: [
                { name: "id", title: "Id", type: "number", width: 50 },
                { name: "to_email", title: "To Email", type: "text" },
                { name: "to_name", title: "To Name", type: "text" },
                { name: "subject", title: "Subject", type: "text" },
                { name: "created_at", title: "Send time", type: "text" },
            ]
        });

    })(jQuery.noConflict());

</script>
