<style type="text/css">
    #zenc-email-logger {
        width: 100%;
        clear: both;
    }
    #jsGridWrapper {
        float: left;
        width: 55%;
        margin-right: 20px;
    }
    #jsViewWrapper {
        float: left;
        width: 43%;
        overflow-x: hidden;
        overflow-y: auto;
        position: relative;
    }
    #jsViewWrapper .tab-wrapper {
        width: 100%;
        height: 360px;
        border: none;
        border-top: 1px solid #f9f9f9;
        border-bottom: 1px solid #f9f9f9;
        margin-bottom: 20px;
        overflow: hidden;
        position: absolute;
        top: 0;
        left: 0;
    }
    #jsViewWrapper .tab-wrapper .contents {
        border-top: 1px solid #f9f9f9;
        margin-top: 25px;
    }
    #jsViewWrapper .codeblock,
    #jsViewWrapper iframe {
        overflow: auto;
        height: 335px;
        width: 100%;
        border: none;
    }
    #jsViewWrapper .codeblock {
        color: ;
    }
    #jsViewWrapper .table {
        width: 100%;
        margin-top: 360px;
    }
    #jsViewWrapper .tab li {
        display: inline-block;
        float: left;
        text-align: center;
        width: 100px;
        padding: 0 10px;
        line-height: 25px;
        border-right: 1px solid #f9f9f9;
        cursor: pointer;
    }
    #jsViewWrapper .tab li.active {
        background: #f9f9f9;
    }
    #jsViewWrapper .tab li:hover {
        background: #c4e2ff;
    }

    @media(max-width: 1200px) {
        #jsGridWrapper, #jsViewWrapper {
            float: none;
            width: 100%;
        }
    }
</style>

<div id="zenc-email-logger">
    <div id="jsGridWrapper">
        <div id="jsGrid"></div>
    </div>
    <div id="jsViewWrapper" class="jsgrid-grid-body">
        Click on an item on the left to see it's contents
    </div>
</div>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jsgrid/1.3.1/jsgrid.min.js"></script>

<script type="text/javascript">

    (function($) {

        function renderTable(data) {
            var $table = $('<table></table>').addClass('jsgrid-table');
            var excludeKeys = ['body_html', 'body_text', 'raw'];

            $.each(data, function(key, value) {
                if ($.inArray(key, excludeKeys) !== -1) {
                    return;
                }

                var $row = $('<tr><td /><td /></tr>');

                $row.find('td:first').css('fontWeight', 'bold').text(
                    !$.isNumeric(key) ? key.replace(/_/g, ' ') : key
                );

                if ($.isPlainObject(value) ||$.isArray(value) || typeof value == 'Object') {
                    $row.find('td:last').append(renderTable(value));
                } else {
                    $row.find('td:last').text(value);
                }
                $table.append($row);
            });
            $table.find('tr:even').addClass('jsgrid-row');
            $table.find('tr:odd').addClass('jsgrid-row');
            $table.find('tr td:first-child').width(130);

            return $table;
        }

        function renderEmail(data) {
            var __createIframe = function(url) {
                var frame = $('<iframe />').width($('#jsViewWrapper').width() - 2);
                if (url) frame.attr('src', url);
                return frame;
            }
            var __createCodeBlock = function(content) {
                return $('<pre />').addClass('codeblock').text(content).width($('#jsViewWrapper').width() - 2);
            }

            $('#jsViewWrapper').empty()
                .append(
                    $('<div />').addClass('tab-wrapper')
                        .append(
                            $('<div />').addClass('tab').append(
                                $('<ul>')
                                  .append($('<li />').text('HTML').addClass('active'))
                                  .append($('<li />').text('Text'))
                                  .append($('<li />').text('Raw'))
                            )
                        )
                        .append(
                            $('<div />').addClass('contents').append(
                                $('<ul>')
                                  .append(
                                      $('<li />').append(
                                          __createIframe("<?php echo Mage::getUrl('zenc_emaillogger/rest/read') ?>?format=html&id=" + data.mail_id)
                                      )
                                  )
                                  .append(
                                      $('<li />').append(
                                          __createCodeBlock(data.body_text)
                                      ).hide()
                                  )
                                  .append(
                                      $('<li />').append(
                                          __createCodeBlock(data.raw)
                                      ).hide()
                                  )
                            )
                        )
                )
                .append($('<div />').addClass('table').append(renderTable(data)))
                .height($('#jsGrid').height());

            $('#jsViewWrapper').find('.tab li').on('click', function() {
                $('#jsViewWrapper').find('.tab li').removeClass('active');
                $(this).addClass('active');
                $('#jsViewWrapper').find('.contents li').hide();
                $('#jsViewWrapper').find('.contents li').eq($(this).index()).show();
            });
        }

        $("#jsGrid").jsGrid({
            width: "100%",

            autoload: true,
            pageLoading: true,
            paging: true,

            rowClick: function(data) {
                $.ajax({
                    type: "GET",
                    url: "<?php echo Mage::getUrl('zenc_emaillogger/rest/read') ?>",
                    data: {id: data.item.id},
                    dataType: "json",
                    success: function(data) {
                        renderEmail(data);
                    }
                });
            },

            controller: {
                loadData: function(filter) {
                    return $.ajax({
                        type: "GET",
                        url: "<?php echo Mage::getUrl('zenc_emaillogger/rest/list') ?>?format=json",
                        data: filter,
                        dataType: "json"
                    });
                }
            },
            fields: [
                { name: "id", title: "Id", type: "number", width: 50 },
                { name: "to_email", title: "To Email", type: "text" },
                { name: "to_name", title: "To Name", type: "text" },
                { name: "subject", title: "Subject", type: "text" },
                { name: "created_at", title: "Send time", type: "text" },
            ]
        });

    })(jQuery.noConflict());

</script>
