<div id="jsGrid"></div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.3.1/jsgrid.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/basicModal/3.3.2/basicModal.min.js"></script>

<script type="text/javascript">
    jQuery.noConflict();
    (function($) {

        function renderTable(data) {
            var $table = $('<table></table>');

            $.each(data, function(key, value) {
                var $row = $('<tr><td /><td /></tr>');

                $row.find('td:first').css('fontWeight', 'bold').text(
                    !$.isNumeric(key) ? key.replace(/_/g, ' ') : key
                );

                if ($.isPlainObject(value) ||$.isArray(value) || typeof value == 'Object') {
                    $row.find('td:last').append(renderTable(value));
                } else {
                    $row.find('td:last').text(value);
                }
                $table.append($row);
            });

            return $table;
        }

        $("#jsGrid").jsGrid({
            width: "100%",

            autoload: true,
            pageLoading: true,
            paging: true,

            rowClick: function(data) {
                $.ajax({
                    type: "GET",
                    url: "<?php echo Mage::getUrl('zenc_emaillogger/rest/read') ?>",
                    data: {id: data.item.id},
                    dataType: "json",
                    success: function(data) {
                        basicModal.show({
                            body: $('<div />').append(renderTable(data)).html(),
                            buttons: {
                                cancel: {
                                    title: 'Close',
                                    fn: basicModal.close
                                }
                            }
                        })
                    }
                });
            },

            controller: {
                loadData: function(filter) {
                    return $.ajax({
                        type: "GET",
                        url: "<?php echo Mage::getUrl('zenc_emaillogger/rest/list') ?>?format=json",
                        data: filter,
                        dataType: "json"
                    });
                }
            },
            fields: [
                { name: "id", title: "Id", type: "number", width: 50 },
                { name: "subject", title: "Subject", type: "text" },
                { name: "created_at", title: "Send time", type: "text" },
            ]
        });

    })(jQuery);
</script>
