checks:
    php:
        fix_php_opening_tag: true
        remove_php_closing_tag: true
        one_class_per_file: false
        side_effects_or_types: true
        no_mixed_inline_html: true
        require_braces_around_control_structures: false
        php5_style_constructor: true
        no_global_keyword: true
        avoid_usage_of_logical_operators: true
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: false
        no_underscore_prefix_in_methods: false
        blank_line_after_namespace_declaration: true
        single_namespace_per_use: false
        psr2_switch_declaration: false
        psr2_control_structure_declaration: false
        avoid_superglobals: true
        security_vulnerabilities: true
        no_exit: true
        uppercase_constants: true
        simplify_boolean_return: true
        remove_extra_empty_lines: true
        parameters_in_camelcaps: true
        optional_parameters_at_the_end: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: '3'
        no_goto: true
        newline_at_end_of_file: true
        line_length:
            max_length: '130'
        function_in_camel_caps: true
        fix_line_ending: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        coding_standard:
            name: Magento
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true
        avoid_unnecessary_concatenation: true

coding_style:
    php:
        braces:
            classes_functions:
                class: new-line
                function: new-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

build_failure_conditions:
    - 'elements.rating(<= C).exists'
    - 'issues.new.exists'
    - 'project.metric("scrutinizer.quality", < 9.99)'
